//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaymentsExample
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public int ld { get; set; }
        public string Name { get; set; }
        public string Icon { get; set; }
    
        public virtual Payment Payment { get; set; }
    }
}
